### PR TITLE
changes

### PR DESCRIPTION
**Pull request by ibrahimbank**
Rename of the pictures

### CODE REVIEW

**Comment by eniolajayi** [comment]
Did you move the aboutUsImages into the image folder?

**Comment by ibrahimbank** [comment]
Nope, you just said to change the name.
bro i sent you some messages on slack

**Comment by eniolajayi** [comment]
Ok, please move them into the images folder. All images will be in the Images folder. It will be easier to maintain especially when we are about to compress and convert them

**Comment by ibrahimbank** [comment]
I'm not seeing any image folder there

**Comment by ibrahimbank** [comment]
I'm only seeing the about image folder i created

**Comment by eniolajayi** [comment]
create a folder for images inside the assets folder

**Comment by ibrahimbank** [comment]
Ok, will do that.

**Comment by ibrahimbank** [comment]
Have created the image folder and moved all pictures there

**Pull request merged**
